/**********************************************************************
Copyright (c) 2026 Contributors. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Contributors:
    ...
**********************************************************************/
package org.datanucleus.enhancer.methods;

import java.lang.reflect.Constructor;
import java.lang.reflect.Method;

import org.datanucleus.enhancer.asm.ClassWriter;
import org.datanucleus.enhancer.asm.MethodVisitor;
import org.datanucleus.enhancer.asm.Opcodes;

import junit.framework.TestCase;

/**
 * Tests for the compound identity code path in NewObjectIdInstance2.
 * Verifies that the enhancer correctly handles PK classes both with and without a String constructor.
 */
public class NewObjectIdInstance2Test extends TestCase
{
    /**
     * Sample compound PK class with a String constructor (JDO-style).
     */
    public static class PKWithStringConstructor
    {
        public int id;
        public String name;

        public PKWithStringConstructor()
        {
        }

        public PKWithStringConstructor(String str)
        {
            // Parse compound key from string representation
            String[] parts = str.split(":");
            this.id = Integer.parseInt(parts[0]);
            this.name = parts[1];
        }
    }

    /**
     * Sample compound PK class without a String constructor (JPA-style IdClass).
     */
    public static class PKWithoutStringConstructor
    {
        public int id;
        public String name;

        public PKWithoutStringConstructor()
        {
        }
    }

    /**
     * Verify that PKWithStringConstructor is detected as having a String constructor.
     * This is the detection logic used in NewObjectIdInstance2.execute().
     */
    public void testDetectsStringConstructor()
    {
        boolean hasStringConstructor = hasStringConstructor(PKWithStringConstructor.class);
        assertTrue("PKWithStringConstructor should be detected as having a String constructor", hasStringConstructor);
    }

    /**
     * Verify that PKWithoutStringConstructor is detected as NOT having a String constructor.
     */
    public void testDetectsMissingStringConstructor()
    {
        boolean hasStringConstructor = hasStringConstructor(PKWithoutStringConstructor.class);
        assertFalse("PKWithoutStringConstructor should be detected as not having a String constructor", hasStringConstructor);
    }

    /**
     * Generate a class with a method that calls "new PKWithStringConstructor((String) key)" and
     * verify the generated bytecode loads and executes correctly.
     */
    public void testGeneratedCodeWithStringConstructor() throws Exception
    {
        String pkClassName = PKWithStringConstructor.class.getName().replace('.', '/');
        byte[] classBytes = generateNewObjectIdMethod("TestHolder1", pkClassName, true);

        Class<?> cls = new ByteArrayClassLoader(getClass().getClassLoader()).defineClass("TestHolder1", classBytes);
        Method m = cls.getMethod("createId", Object.class);

        Object result = m.invoke(null, "42:test");
        assertNotNull(result);
        assertTrue("Should return an instance of PKWithStringConstructor", result instanceof PKWithStringConstructor);
        PKWithStringConstructor pk = (PKWithStringConstructor) result;
        assertEquals(42, pk.id);
        assertEquals("test", pk.name);
    }

    /**
     * Generate a class with a method that calls "new PKWithoutStringConstructor()" and
     * verify the generated bytecode loads and executes correctly.
     */
    public void testGeneratedCodeWithoutStringConstructor() throws Exception
    {
        String pkClassName = PKWithoutStringConstructor.class.getName().replace('.', '/');
        byte[] classBytes = generateNewObjectIdMethod("TestHolder2", pkClassName, false);

        Class<?> cls = new ByteArrayClassLoader(getClass().getClassLoader()).defineClass("TestHolder2", classBytes);
        Method m = cls.getMethod("createId", Object.class);

        Object result = m.invoke(null, "ignored");
        assertNotNull(result);
        assertTrue("Should return an instance of PKWithoutStringConstructor", result instanceof PKWithoutStringConstructor);
    }

    /**
     * Mirrors the constructor detection logic from NewObjectIdInstance2.execute().
     */
    private static boolean hasStringConstructor(Class<?> cls)
    {
        try
        {
            cls.getConstructor(new Class[] {String.class});
            return true;
        }
        catch (Exception e)
        {
            return false;
        }
    }

    /**
     * Generates bytecode for a class with a static method "createId(Object key)" that either:
     * - calls new PK((String) key)  if useStringCtor is true
     * - calls new PK()             if useStringCtor is false
     *
     * This mirrors exactly what NewObjectIdInstance2.execute() generates for the compound identity branch.
     */
    private byte[] generateNewObjectIdMethod(String className, String pkClassInternalName, boolean useStringCtor)
    {
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
        cw.visit(Opcodes.V11, Opcodes.ACC_PUBLIC, className, null, "java/lang/Object", null);

        MethodVisitor mv = cw.visitMethod(
            Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC, "createId",
            "(Ljava/lang/Object;)Ljava/lang/Object;", null, null);
        mv.visitCode();

        if (useStringCtor)
        {
            mv.visitTypeInsn(Opcodes.NEW, pkClassInternalName);
            mv.visitInsn(Opcodes.DUP);
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitTypeInsn(Opcodes.CHECKCAST, "java/lang/String");
            mv.visitMethodInsn(Opcodes.INVOKESPECIAL, pkClassInternalName, "<init>", "(Ljava/lang/String;)V", false);
        }
        else
        {
            mv.visitTypeInsn(Opcodes.NEW, pkClassInternalName);
            mv.visitInsn(Opcodes.DUP);
            mv.visitMethodInsn(Opcodes.INVOKESPECIAL, pkClassInternalName, "<init>", "()V", false);
        }

        mv.visitInsn(Opcodes.ARETURN);
        mv.visitMaxs(3, 1);
        mv.visitEnd();

        cw.visitEnd();
        return cw.toByteArray();
    }

    /**
     * Simple classloader that can define a class from a byte array.
     */
    private static class ByteArrayClassLoader extends ClassLoader
    {
        ByteArrayClassLoader(ClassLoader parent)
        {
            super(parent);
        }

        Class<?> defineClass(String name, byte[] bytes)
        {
            return defineClass(name, bytes, 0, bytes.length);
        }
    }
}
